<a href="https://colab.research.google.com/github/Arjita15/AI_LAB/blob/main/lab3/arjita_ACE080BCT015_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to PyTorch

PyTorch is a widely used open-source framework for machine learning and deep learning applications. It provides a flexible environment for building, training, and deploying neural network models. Due to its dynamic computational graph and ease of use, PyTorch has become a popular choice among researchers, students, and industry practitioners. The framework supports efficient numerical computation on both CPUs and GPUs, making it suitable for developing complex artificial intelligence solutions.

## Why use PyTorch?
Machine learning researchers love using PyTorch. And as of February 2022, PyTorch is the most used deep learning framework on Papers With Code, a website for tracking machine learning research papers and the code repositories attached with them.

PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.

And if companies such as Tesla and Meta (Facebook) use it to build models they deploy to power hundreds of applications, drive thousands of cars and deliver content to billions of people, it's clearly capable on the development front too.

In [ ]:
import torch
print(torch.__version__)

2.11.0+cpu


## 1. Introduction to Tensor, Vector, Scalar and Matrix

### 1.1 Scalar

A scalar is the simplest form of a tensor and contains only a single numerical value. Since it represents just one quantity, it has no dimensions. Scalars are commonly used to represent individual measurements, constants, or computed values such as loss during model training.

In [ ]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
print(scalar.ndim)
print(scalar.item())
print(scalar.shape)

0
7
torch.Size([])


### 1.2 Vector

A vector is a one-dimensional tensor consisting of multiple numerical values arranged in sequence. Vectors are useful for representing features, coordinates, or collections of related measurements. The dimensionality of a vector is determined by its length.

In [ ]:
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [ ]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


### 1.3 Matrix

A matrix is a two-dimensional tensor organized into rows and columns. Matrices are frequently used to represent structured datasets, mathematical transformations, and grayscale images. Each element within a matrix can be accessed using its row and column position.

In [ ]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


### 1.4 Tensor

Tensors are the fundamental data structures in PyTorch and form the basis of all computations in deep learning. They provide a way to represent numerical information in multiple dimensions and are used to store and process data such as images, text, audio, and videos.

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


### 1.4.1 Random Tensors

Random tensors contain values generated randomly according to a specified distribution. These tensors are often used for initializing neural network parameters, generating sample data, and testing algorithms during development.

In [ ]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.7787, 0.4017, 0.8086],
         [0.6240, 0.7859, 0.1437]]),
 torch.float32)

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### 1.4.2 Tensors of only Zeros and Ones





PyTorch provides methods for creating tensors containing only zeros or only ones. Such tensors are useful for initializing model parameters, creating masks, and performing various numerical operations.

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### 1.4.3 Creating a range and tensors like

Range-based tensors allow the generation of numerical sequences within a specified interval. These tensors are commonly used for indexing, iteration, and creating structured datasets. Modern PyTorch implementations recommend using torch.arange() for generating sequences efficiently.

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Can also create a tensor of zeros similar to another tensor
# will have same shape
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 1.4.4 Tensor datatypes

PyTorch supports multiple tensor data types to balance computational efficiency and memory usage. The most frequently used data type is float32, which provides a good compromise between precision and performance.

Common data types include:

* float16 – 16-bit floating-point values
* float32 – 32-bit floating-point values
* float64 – 64-bit floating-point values
* Integer data types of varying precision
* Boolean data types for logical operations

Selecting an appropriate data type is important because it affects both memory consumption and computational speed.

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                  dtype=torch.float16)

float_16_tensor.dtype

torch.float16

## 2. Getting information from tensors

Several tensor attributes provide useful information about stored data:

* Shape: Describes the dimensions of a tensor.
* Data Type (dtype): Specifies how the tensor values are stored in memory.
* Device: Indicates whether the tensor is stored on the CPU or GPU.

Understanding these properties is essential for ensuring compatibility between tensors during mathematical operations.

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.5682, 0.9598, 0.6705, 0.9043],
        [0.3060, 0.4899, 0.6035, 0.5777],
        [0.0282, 0.7886, 0.4572, 0.9636]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. Tensor Operations

Deep learning relies heavily on mathematical operations performed on tensors. During model training, these operations are repeatedly executed to learn patterns and relationships within data.

Common tensor operations include:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication
* Aggregation Functions

These operations form the computational foundation of neural networks and other machine learning algorithms.

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


### Matrix Multiplication

Matrix multiplication is one of the most important operations in deep learning because neural networks perform numerous matrix calculations during forward and backward propagation.

Two key rules must be satisfied:

* The inner dimensions of the matrices must be equal.
* The resulting matrix shape is determined by the outer dimensions.

Failure to satisfy these requirements results in shape mismatch errors, which are among the most common issues encountered in deep learning implementations.

In [ ]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


### One of the most common errors in deep learning (shape errors)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                          [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # This cause error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Aggregation Operations

Aggregation functions summarize tensor values and are useful for data analysis and model evaluation. Frequently used aggregation operations include:

* Minimum value
* Maximum value
* Mean value
* Sum of elements

These functions help extract meaningful statistical information from tensors.



In [ ]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # Not work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


### Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively. This is helpful incase we just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change Tensor Datatype

PyTorch allows tensors to be converted from one data type to another. Data type conversion is often necessary when combining tensors, optimizing memory usage, or preparing data for specific computations.

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

### Reshaping

Reshaping changes the structure of a tensor without modifying its underlying data. This operation is particularly useful when preparing data for neural network layers that require specific input dimensions.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
x, x.shape

### View
The view operation provides an alternative representation of the same tensor data with a different shape. Since the new tensor shares the original memory, changes made through the view are reflected in the original tensor.

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

### Reshape vs View
Although both operations alter tensor shapes, they differ in implementation. The view operation requires compatible memory layout and shares existing data, whereas reshape is more flexible and may create a copy if necessary.

In [ ]:
import torch
x = torch.arange(6)

# print(x,x.shape)
a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


### Stack
Stacking combines multiple tensors along a newly created dimension. This operation is frequently used when organizing multiple samples into batches for training machine learning models.

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [ ]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

### Squeeze and Unsqueeze functions

The squeeze operation removes dimensions of size one, while unsqueeze adds a new dimension of size one. These operations help adjust tensor shapes to satisfy model input requirements and matrix multiplication rules.

In [ ]:
# using squeeze and unsqueeze functions
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


### Permutation

Permutation rearranges the order of tensor dimensions without changing the underlying values. This functionality is particularly useful when working with image and sequence data where specific dimension ordering is required.

Because permutation returns a view of the original tensor, modifications made to the permuted tensor can affect the original tensor as well.

In [ ]:
import torch
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)
y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


## 4. Indexing (selecting data from tensors)

Indexing enables access to specific elements or subsets of a tensor. By specifying positions along different dimensions, users can retrieve, modify, or analyze particular portions of the data efficiently.

PyTorch also supports slicing operations, allowing access to ranges of values and entire dimensions through concise notation.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1]) # Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## 5. Pytorch Tensor to NumPy arrays and vice versa

PyTorch and NumPy work closely together, allowing seamless conversion between tensors and arrays.

The primary conversion methods are:

* Converting a NumPy array into a PyTorch tensor.
* Converting a PyTorch tensor into a NumPy array.

This interoperability is useful when combining PyTorch with scientific computing libraries that rely on NumPy.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 6. Tensors on GPU
One of PyTorch's major advantages is its ability to utilize Graphics Processing Units (GPUs) for accelerated computation. GPUs contain thousands of processing cores capable of performing large-scale numerical calculations in parallel.

Moving tensors and models to a GPU can significantly reduce training time, especially for deep learning applications involving large datasets and complex neural network architectures. Therefore, GPU acceleration plays a critical role in modern artificial intelligence development.

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Discussion

This lab provided a comprehensive introduction to PyTorch fundamentals. We delved into various tensor types—scalars, vectors, matrices, and multi-dimensional tensors—and explored their creation and properties. Key tensor operations, including arithmetic, matrix multiplication, reshaping, indexing, stacking, and dimension manipulation, were implemented to illustrate how data is handled in deep learning. The seamless interchange between PyTorch tensors and NumPy arrays was also demonstrated, emphasizing their interoperability. Additionally, the lab touched upon GPU acceleration, showcasing PyTorch's capability to speed up computations for demanding machine learning workloads. These hands-on exercises fostered a practical understanding of tensor operations and PyTorch's essential features.

## Conclusion

In summary, this lab effectively covered the foundational concepts and operations within PyTorch. Through practical exercises, participants gained hands-on experience in tensor creation, modification, and computation. Critical areas such as tensor characteristics, matrix operations, reshaping methodologies, and GPU leverage were thoroughly examined and applied. This laboratory session has thus laid a solid groundwork for comprehending PyTorch's data handling and computational paradigms. The insights acquired are invaluable for forthcoming endeavors in neural networks, deep learning models, and other sophisticated machine learning applications.